#!/bin/bash
# Retrieve a GitHub users email

ghmail() {
	local repo=""

	if [[ $2 == "" ]]; then
		repo=`curl "https://api.github.com/users/$1/repos?type=owner&sort=updated" -s | sed -En 's|"name": "(.+)",|\1|p' | tr -d ' ' | head -n 1`
	else
		repo="$2"
	fi

	curl "https://api.github.com/repos/$1/${repo}/commits" -s | sed -En 's|"(email\|name)": "(.+)",?|\2|p' | tr -s ' ' | paste - - | sort -u -k 1,1
}
