#!/bin/bash
# apm package installation

run_apm() {
    # Check for apm
    if type_exists 'apm'; then
        log_header "Installing Atom packages..."

        # List of apm packages
        local -a packages=(
            'auto-update-packages'
            'autocomplete-plus'
            'autoprefixer'
            'editorconfig'
            'jshint'
            'language-jade'
            'merge-conflicts'
            'sort-lines'
            'spacegray-dark-ui'
            'status-tab-spacing'
            'tabs-to-spaces'
            'tomorrow-night-eighties-syntax'
            'travis-ci-status'
            'uglify'
            'visual-bell'
        )

        # Install packages
        for index in ${!packages[*]}
        do
            apm install ${packages[$index]}
        done

        [[ $? ]] && log_success "Done"
    else
        printf "\n"
        log_error "Error: apm not found."
        printf "Aborting...\n"
        exit
    fi
}
