#!/bin/bash
# APT package installation

run_apt() {
    # Check for APT
    if type_exists 'apt-get'; then
        log_header "Updating any existing APT packages..."
        # Upgrade any already-installed packages
        sudo apt-get -qq update
        sudo apt-get -qq upgrade
        [[ $? ]] && log_success "Done"

        log_header "Checking status of desired APT repositories..."
        if ! type_exists 'add-apt-repository'; then
            sudo apt-get -qq install python-software-properties
        fi

        local list_repositories
        local -a missing_repositories
        local -a desired_repositories=(
            'chris-lea/node.js'
            'webupd8team/sublime-text-3'
        )

        for index in ${!desired_repositories[*]}
        do
            if ! ppa_exists ${desired_repositories[$index]}; then
                # Store the name of every missing repository
                missing_repositories=("${missing_repositories[@]}" "ppa:${desired_repositories[$index]}")
            fi
        done

        if [[ "${missing_repositories}" ]]; then
            # Convert the array of missing repositories into a list of
            # space-separated strings
            list_repositories=$( printf "%s " "${missing_repositories[@]}" )

            log_header "Adding missing APT repositories..."
            # Add all missing repositories
            sudo add-apt-repository -y ${list_repositories}
            sudo apt-get -qq update

            [[ $? ]] && log_success "Done"
        fi

        log_header "Checking status of desired APT packages..."
        local list_packages
        local -a missing_packages
        local -a desired_packages=(
            'build-essential'
            'git-core'
            'libssl-dev'
            'nodejs'
            'sublime-text-installer'
            'tmux'
            'tree'
            'wget'
        )

        for index in ${!desired_packages[*]}
        do
            if ! package_exists ${desired_packages[$index]}; then
                # Store the name (and options) of every missing package
                missing_packages=("${missing_packages[@]}" "${desired_packages[$index]}")
            fi
        done

        if [[ "${missing_packages}" ]]; then
            # Convert the array of missing packages into a list of
            # space-separated strings
            list_packages=$( printf "%s " "${missing_packages[@]}" )

            log_header "Installing missing APT packages..."
            # Install all missing packages
            sudo apt-get -qq install ${list_packages}

            [[ $? ]] && log_success "Done"
        fi
    else
        printf "\n"
        log_error "Error: APT not found."
        printf "Aborting...\n"
        exit
    fi
}
