#!/bin/bash
# brew

run_brew() {
    # Check for Homebrew
    if type_exists 'brew'; then
        log_header "Updating Homebrew..."

        # Use the latest version of Homebrew
        brew update
        [[ $? ]] && log_success "Done"

        log_header "Updating any existing Homebrew formulae..."

        # Upgrade any already-installed formulae
        brew upgrade
        [[ $? ]] && log_success "Done"

        local list_formulae
        local -a missing_formulae
        local -a desired_formulae=(
            'coreutils'
            'git'
            'ack'
            'bash'
            'bash-completion'
            'tree'
            'wget'
        )

        # Store the name (and options) of every missing formula
        for i in ${!desired_formulae[*]}
        do
            if ! formula_exists ${desired_formulae[$i]}; then
                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$i]}")
            fi
        done

        if [[ "${missing_formulae}" ]]; then
            # Convert the array of missing formula into a list of space-separate strings
            list_formulae=$( printf "%s " "${missing_formulae[@]}" )

            log_header "Installing missing Homebrew formulae..."

            # Install all missing formulae
            brew install ${list_formulae}
            [[ $? ]] && log_success "Done"
        fi

        # Install latest rsync
        brew install https://raw.github.com/Homebrew/homebrew-dupes/master/rsync.rb

        # Remove outdated versions from the Cellar
        brew cleanup
    else
        printf "\n"
        log_error "Error: Homebrew not found"
        printf "Aborting...\n"
        exit
    fi
}
