#!/bin/bash

run_help() {
cat <<EOT

Windows and OS X dotfiles - Kevin Martensson - http://kevinmartensson.com/

Usage: $(basename "$0") [options]

Options:
  --no-packages   Suppress package updates
  --no-sync       Suppress pulling from the remote repository
  -?, -h, --help  Show this message

Documentation can be found at https://github.com/kevva/dotfiles/

Copyright (c) Nicolas Gallagher
Licensed under the MIT license.
EOT
}
