#!/bin/bash
# help

run_help() {
cat <<EOT
dotfiles - Kevin Martensson - http://kevinmartensson.com/

Usage: $(basename "$0") [options]

Options:
    -h,  --help          Print this help text
    -np, --no-packages   Suppress package updates
    -ns, --no-sync       Suppress pulling from the remote repository

Documentation can be found at https://github.com/kevva/dotfiles/

Copyright (c) Kevin Martensson
Licensed under the MIT license.
EOT
}
