#!/bin/bash
# npm package installation

run_npm() {
    # Check for npm
    if type_exists 'npm'; then
        log_header "Installing Node.js packages..."

        # Give permissions
        sudo chown -R ${USER} /usr/local

        # List of npm packages
        local packages="bower component gulp jshint yo"

        # Install packages globally and quietly
        npm install ${packages} --global --quiet

        [[ $? ]] && log_success "Done"
    else
        printf "\n"
        log_error "Error: npm not found."
        printf "Aborting...\n"
        exit
    fi
}
