#!/bin/bash
# npm

run_npm() {
	# Check for npm
	if type_exists 'npm'; then
		# Setup global packages directory
		mkdir -p "${HOME}/.npm-packages"

		# Config npm
		npm config set prefix "${HOME}/.npm-packages"
		npm config set email "kevinmartensson@gmail.com"

		log_header "Updating any existing npm packages..."

		# Update any already-installed packages
		npm update --global --quiet
		[[ $? ]] && log_success "Done"

		local list_packages
		local -a missing_packages
		local -a desired_packages=(
			'duo'
			'empty-trash'
			'gulp'
			'imagemin'
			'jscs'
			'jshint'
			'trash'
		)

		# Store the name (and options) of every missing package
		for i in ${!desired_packages[*]}
		do
			if ! type_exists ${desired_packages[$i]}; then
				missing_packages=("${missing_packages[@]}" "${desired_packages[$i]}")
			fi
		done

		if [[ "${missing_packages}" ]]; then
			# Convert the array of missing packages into a list of space-separate strings
			list_packages=$( printf "%s " "${missing_packages[@]}" )

			log_header "Installing missing npm packages..."

			# Install all missing packages
			npm install --global --quiet ${list_packages}
			[[ $? ]] && log_success "Done"
		fi
	else
		printf "\n"
		log_error "Error: npm not found"
		printf "Aborting...\n"
		exit 1
	fi
}
