#!/bin/bash
# Install Sublime Text 3 preferences

run_subl() {
    SUBLIME_DOTFILES="${DOTFILES_DIRECTORY}/subl"
    SUBLIME_DIRECTORY="${HOME}/Library/Application Support/Sublime Text 3/Packages"
    SUBLIME_USER_DIRECTORY="${SUBLIME_DIRECTORY}/User"

    # Create symlink
    ln -fs "${SUBLIME_DOTFILES}" "${SUBLIME_USER_DIRECTORY}"

    # Install packages
    declare -a packages=(
        "https://github.com/emmetio/sublime-tern.git TernJS"
        "https://github.com/tednaleid/sublime-EasyMotion.git --branch st3 EasyMotion"
        "https://github.com/SublimeLinter/SublimeLinter.git --branch sublime-text-3 SublimeLinter"
    )

    for index in ${!packages[*]}
    do
        PKG_DIRECTORY=$(echo ${packages[$index]} | awk '{ print $NF }')

        cd "${SUBLIME_DIRECTORY}"

        if [[ ! -d "${PKG_DIRECTORY}" ]]; then
            git clone ${packages[$index]}
        else
            cd "${PKG_DIRECTORY}"
            git pull --rebase
        fi
    done

    [[ $? ]] && log_success "Sublime Text 3 settings updated!"
}
