#!/bin/bash
# Sublime Text 3 preferences

run_subl() {
    SUBLIME_DOTFILES="${DOTFILES_DIRECTORY}/subl"
    if is_os 'darwin'; then
        SUBLIME_DIRECTORY="${HOME}/Library/Application Support/Sublime Text 3/Packages"
    elif is_os 'linux'; then
        SUBLIME_DIRECTORY="${HOME}/.config/sublime-text-3/Packages"
    elif is_os 'msys'; then
        SUBLIME_DIRECTORY="${APPDATA}/Sublime Text 3/Packages"
    fi
    SUBLIME_USER_DIRECTORY="${SUBLIME_DIRECTORY}/User"

    log_header "Writing Sublime Text 3 preferences..."
    # If the User directory exists, remove it
    if [[ -d "${SUBLIME_USER_DIRECTORY}" ]]; then
        rm -rf "${SUBLIME_USER_DIRECTORY}"
    fi
    # Symlink the folder
    ln -fs "${SUBLIME_DOTFILES}" "${SUBLIME_USER_DIRECTORY}"

    # Create `~/bin` if it doesn't exist
    if [[ ! -d "${HOME}/bin" ]]; then
         mkdir "${HOME}/bin"
    fi

    # Create CLI symlink
    if is_os 'darwin' && [[ ! -r "${HOME}/bin/slt" ]]; then
        ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" "${HOME}/bin/slt"
    elif is_os 'linux' && [[ ! -r "${HOME}/bin/slt" ]]; then
        ln -s "/usr/bin/subl" "${HOME}/bin/slt"
    elif is_os 'msys' && [[ ! -r "${HOME}/bin/slt" ]]; then
tee <<EOF > ${HOME}/bin/slt
"${PROGRAMFILES}/Sublime Text 3/sublime_text.exe" "\$@"
EOF
    fi
    [[ $? ]] && log_success "Done"
}
