#!/bin/bash

# Header logging
e_header() {
  echo -e "\n\033[0;37m$@\033[m";
}

# Success logging
e_success() {
  echo -e "\033[0;32m✓ $@\033[m";
}

# Error logging
e_error() {
  echo -e "\033[0;31mx $@\033[m";
}

# Warning logging
e_warning() {
  echo -e "\033[0;33m! $@\033[m";
}

# Test whether a command exists
# $1 - cmd to test
type_exists() {
  if [[ `type -P $1` ]]; then
    return 0
  fi
  return 1
}

# Test whether a Homebrew formula is already installed
# $1 - formula name (may include options)
formula_exists() {
  if ! `brew list $1 >/dev/null`; then
    e_warning "Missing formula: $1"
    return 1
  fi

  echo $1 "already installed."
  return 0
}

# Test which OS the user runs
# $1 - cmd to test
os_is() {
  if [[ "$OSTYPE" == $1* ]]; then
    return 0
  fi
  return 1
}
