#!/bin/bash

# aliases

# Allow aliases to be with sudo
alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
else # OS X `ls`
  colorflag="-G"
fi

# List all files colorized in long format
alias l="ls -l ${colorflag}"

# List all files colorized in long format, including dot files
alias la="ls -lAh ${colorflag}"

# List only directories
alias lsd="ls -l ${colorflag} | grep "^d""

# Always use color output for `ls`
alias ls="command ls ${colorflag}"
export LS_COLORS="no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# Copy my public key to my clipboard
if [[ $OSTYPE == darwin* ]]; then
  # OS X
  alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"
elif [[ $OSTYPE == msys* ]]; then
  # Windows
  alias pubkey="cat ~/.ssh/id_rsa.pub | clip | printf '=> Public key copied to pasteboard.\n'"
fi

# Get npm updates, and their installed packages
alias update="npm update npm -g; npm update -g"

# Empty the Trash
if [[ $OSTYPE == darwin* ]]; then
  # Also, clear Apple’s System Logs to improve shell startup speed
  alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"
elif [[ $OSTYPE == msys* ]]; then
  alias emptytrash="rm -rf '$SYSTEMDRIVE/\$Recycle.bin'"
fi

# OS X specific
if [[ $OSTYPE == darwin* ]]; then
  # Flush DNS cache
  alias flushdns="dscacheutil -flushcache"

  # Recursively delete `.DS_Store` files
  alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

  # Show/hide hidden files in Finder
  alias showdotfiles="defaults write com.apple.Finder AppleShowAllFiles -bool true && killall Finder"
  alias hidedotfiles="defaults write com.apple.Finder AppleShowAllFiles -bool false && killall Finder"

  # Hide/show all desktop icons (useful when presenting)
  alias showdeskicons="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
  alias hidedeskicons="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
fi
