#!/bin/bash

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~"
alias -- -="cd -"

# Enable aliases to be sudo'ed
alias sudo="sudo "

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then
	colorflag="--color"
else
	colorflag="-G"
fi

# List all files colorized in long format
alias l="ls -lAhF ${colorflag}"
