#!/bin/bash

# bash_path

if [[ $OSTYPE == darwin* ]]; then
  # OS X
  declare -a bins=(
    "/usr/bin"
    "$HOME/bin"
    "$HOME/.dotfiles/bin"
    "$HOME/.rvm/bin"
    "$(brew --prefix coreutils)/libexec/gnubin" # Add brew-installed GNU core utilities bin
    "$(brew --prefix)/share/npm/bin" # Add npm-installed package bin
  )
elif [[ $OSTYPE == msys* ]]; then
  # Windows
  declare -a bins=(
    "$HOME/.dotfiles/bin"
  )
fi

# If these bins exist, then add them to the PATH
for index in ${!bins[*]}
do
  if [ -d ${bins[$index]} ]; then
    PATH="$PATH:${bins[$index]}"
  fi
done

unset bins

export PATH
