#!/bin/bash
# bash_profile

# Set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
	export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
	export TERM=xterm-256color
fi

# Load files
load_dotfiles() {
	export NVM_DIR="${HOME}/.nvm"

	if [ -s "${NVM_DIR}/nvm.sh" ]; then
		source "${NVM_DIR}/nvm.sh"
	fi

	declare -a files=(
		"${HOME}/.dotfiles/bash/bash_options"
		"${HOME}/.dotfiles/bash/bash_exports"
		"${HOME}/.dotfiles/bash/bash_aliases"
		"${HOME}/.dotfiles/bash/functions/"*
		"${HOME}/.dotfiles/bash/bash_prompt"
		"${HOME}/.dotfiles/bash/bash_paths"
		"${HOME}/.bash_profile.local"
	)

	# If these files are readable, source them
	for i in ${!files[*]}
	do
		if [[ -r ${files[$i]} ]]; then
			source "${files[$i]}"
		fi
	done

	# Source bash completion on OS X
	if [[ $(type -P brew) ]] && [[ -r "$(brew --prefix)/etc/bash_completion" ]]; then
		source "$(brew --prefix)/etc/bash_completion"
	fi
}

load_dotfiles
unset load_dotfiles
