#!/bin/bash
# bash_aliases

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~"
alias -- -="cd -"

# Enable aliases to be sudo'ed
alias sudo='sudo '

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then
    colorflag="--color"
else
    colorflag="-G"
fi

# List all files colorized in long format
alias l="ls -lAh ${colorflag}"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# Flush DNS cache
if [[ $(type -P dscacheutil) ]]; then
    alias flushdns="dscacheutil -flushcache"
fi
