#!/bin/bash

# bash_profile

declare -a files=(
  "$HOME/.dotfiles/bash/bash_config" # Configuration
  "$HOME/.dotfiles/bash/bash_aliases" # Aliases
  "$HOME/.dotfiles/bash/bash_functions" # Functions
  "$HOME/.dotfiles/bash/bash_prompt" # Custom Bash prompt
  "$HOME/.bash_profile.local" # Local and private settings
  "$HOME/.dotfiles/bash/bash_path" # Path modification
)

# If these files are readable, source them
for index in ${!files[*]}
do
  if [ -r ${files[$index]} ]; then
    source ${files[$index]}
  fi
done

unset files

if [[ $OSTYPE == darwin* ]]; then
  # Only use `brew` after it has been added to the PATH
  bash_completion_path="$(brew --prefix)/etc/bash_completion"

  # Source Bash completion (installed via Homebrew)
  if [[ -r $bash_completion_path ]]; then
    source $bash_completion_path
  fi
fi
