#!/bin/bash
# bash_prompt

# Example:
# kevva@host: ~/.dotfiles on master [+!?$]
# ❯

if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

# Git status information
prompt_git() {
    local s=""
    local branchName=""

    # Check if the current directory is in a git repository
    if [ $(git rev-parse --is-inside-work-tree &>/dev/null; printf "%s" $?) == 0 ]; then
        # Check if the current directory is in .git before running git checks
        if [ "$(git rev-parse --is-inside-git-dir 2> /dev/null)" == "false" ]; then
            # Ensure index is up to date
            git update-index --really-refresh  -q &>/dev/null

            # Check for uncommitted changes in the index
            if ! $(git diff --quiet --ignore-submodules --cached); then
                s="$s+";
            fi

            # Check for unstaged changes
            if ! $(git diff-files --quiet --ignore-submodules --); then
                s="$s!";
            fi

            # Check for untracked files
            if [ -n "$(git ls-files --others --exclude-standard)" ]; then
                s="$s?";
            fi

            # Check for stashed files
            if $(git rev-parse --verify refs/stash &>/dev/null); then
                s="$s$";
            fi
        fi

        # Get the short symbolic ref
        # If HEAD isn't a symbolic ref, get the short SHA
        # Otherwise, just give up
        branchName="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
                      git rev-parse --short HEAD 2> /dev/null || \
                      printf "(unknown)")"

        [ -n "$s" ] && s=" [$s]"

        printf "%s" "$1$branchName$s"
    else
        return
    fi
}

set_prompts() {
    local black=""
    local blue=""
    local bold=""
    local cyan=""
    local green=""
    local orange=""
    local purple=""
    local red=""
    local reset=""
    local white=""
    local yellow=""

    local hostStyle=""
    local userStyle=""

    # Solarized colors
    # (https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized#the-values)
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        tput sgr0 # reset colors
        bold=$(tput bold)
        reset=$(tput sgr0)
        black=$(tput setaf 0)
        blue=$(tput setaf 33)
        cyan=$(tput setaf 37)
        green=$(tput setaf 64)
        orange=$(tput setaf 166)
        purple=$(tput setaf 125)
        red=$(tput setaf 124)
        white=$(tput setaf 15)
        yellow=$(tput setaf 136)
    else
        bold=""
        reset="\e[0m"
        black="\e[1;30m"
        blue="\e[0;34m"
        cyan="\e[0;36m"
        green="\e[0;32m"
        orange="\e[1;33m"
        purple="\e[1;35m"
        red="\e[0;31m"
        white="\e[1;37m"
        yellow="\e[0;33m"
    fi

    # Logged in as root
    if [[ "$USER" == "root" ]]; then
        userStyle="\[$bold$red\]"
    else
        userStyle="\[$orange\]"
    fi

    # Connected via ssh
    if [[ "$SSH_TTY" ]]; then
        hostStyle="\[$bold$red\]"
    else
        hostStyle="\[$yellow\]"
    fi

    # Set the terminal title to the current working directory
    PS1="\[\033]0;\w\007\]"

    # Build the prompt
    PS1+="\n" # Newline
    PS1+="\[$userStyle\]\u" # Username
    PS1+="\[$reset$white\]@" # @
    PS1+="\[$hostStyle\]\h" # Host
    PS1+="\[$reset$white\]: " # :
    PS1+="\[$green\]\w" # Working directory
    PS1+="\$(prompt_git \"$white on $cyan\")" # Git repository details
    PS1+="\n" # Newline
    PS1+="\[$reset$white\]❯ \[$reset\]" # ❯ (and reset color)

    export PS1
}

set_prompts
unset set_prompts
