#!/bin/bash
# bash_paths

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
    # Ensure that this bin always takes precedence over `/usr/bin`
    "/usr/local/bin"
)

# Directories to be appended to PATH
declare -a dirs_to_append=(
    "/usr/bin"
    "${HOME}/bin"
    "${HOME}/.npm-packages"
    "${HOME}/.dotfiles/bin"
    "$(brew --prefix coreutils)/libexec/gnubin"
    "$(brew --prefix)/share/npm/bin"
)

# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}
do
    if [ -d ${dirs_to_prepend[$index]} ]; then
        # If these directories exist, then prepend them to existing PATH
        PATH="${dirs_to_prepend[$index]}:${PATH}"
    fi
done

# Append directories to PATH
for index in ${!dirs_to_append[*]}
do
    if [ -d ${dirs_to_append[$index]} ]; then
        # If these bins exist, then append them to existing PATH
        PATH="${PATH}:${dirs_to_append[$index]}"
    fi
done

# Append npm global packages directory to NODE_PATH
NODE_PATH="${HOME}/.npm-packages/lib/node_modules:${NODE_PATH}"

unset MANPATH
unset dirs_to_prepend dirs_to_append brew_to_append

# Ensure we'll find installed binaries and man pages
MANPATH="${HOME}/.npm-packages/share/man:$(manpath)"

export PATH
