#!/bin/bash
# bash_profile

load_dotfiles() {
    declare -a files=(
        "${HOME}/.rvm/scripts/rvm"
        "${HOME}/.dotfiles/bash/bash_config"
        "${HOME}/.dotfiles/bash/bash_aliases"
        "${HOME}/.dotfiles/bash/functions/"*
        "${HOME}/.dotfiles/bash/bash_prompt"
        "${HOME}/.dotfiles/bash/bash_paths"
        "$(brew --prefix)/etc/bash_completion"
        "${HOME}/.bash_profile.local"
    )

    # If these files are readable, source them
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source "${files[$index]}"
        fi
    done
}

load_dotfiles
unset load_dotfiles

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
if [[ -e "${HOME}/.ssh/config" ]]; then
    complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2 | tr ' ' '\n')" scp sftp ssh
fi
