#!/bin/bash

# exports

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

# Set title to current path
export PROMPT_COMMAND='printf -ne "\033]0;${PWD/$HOME/~}\007"'

if [[ "$OSTYPE" == darwin* ]]; then
  # OS X
  declare -a bins=(
    "/usr/bin"
    "$HOME/bin"
    "$HOME/.dotfiles/bin"
    "$HOME/.rvm/bin"
    "$(brew --prefix coreutils)/libexec/gnubin" # Add brew-installed GNU core utilities bin
    "$(brew --prefix)/share/npm/bin" # Add npm-installed package bin
  )
elif [[ "$OSTYPE" == msys* ]]; then
  # Windows
  declare -a bins=(
    "$HOME/.dotfiles/bin"
  )
fi

# If these bins exist, then add them to the PATH
for index in ${!bins[*]}
do
  if [ -d ${bins[$index]} ]; then
    PATH="$PATH:${bins[$index]}"
  fi
done

unset bins

export PATH
