#!/bin/bash

# exports

# Make Sublime Text 2 the default editor
export EDITOR="sublime_text -w"

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="ls:ls *:cd:cd -:pwd;exit:date:* --help"

declare -a bins=(
  "/usr/bin"
  "$HOME/bin"
  "$HOME/.dotfiles/bin"
  "$HOME/.rvm/bin"
)

# If these bins exist, then add them to the PATH
for index in ${!bins[*]}
do
  if [ -d ${bins[$index]} ]; then
    PATH="$PATH:${bins[$index]}"
  fi
done

unset bins

export PATH
